# Generated by Django 6.0.3 on 2026-03-25 03:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Public name of the app (e.g. 'Inventory Pro')", max_length=100)),
                ('system_slug', models.SlugField(help_text="Unique identifier used for routing (e.g. 'inventory-pro')", unique=True)),
                ('description', models.TextField(blank=True, help_text='Detailed explanation of what the app does for the marketplace.')),
                ('url_conf_path', models.CharField(help_text="The Python path to the app's URLs, e.g., 'apps.demo.small_biz.inventory.urls'", max_length=255)),
                ('icon_class', models.CharField(default='fas fa-cube', help_text='FontAwesome class for the dashboard icon.', max_length=50)),
                ('is_premium', models.BooleanField(default=False, help_text='If true, only tenants with premium subscriptions can see/use this.')),
                ('is_active', models.BooleanField(default=True, help_text='If inactive, the app is hidden from all catalogs and dashboards.')),
            ],
            options={
                'verbose_name': 'Global Application',
                'verbose_name_plural': 'Global Applications',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='GlobalDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='registry.globalapp')),
            ],
            options={
                'verbose_name': 'Global Department',
                'verbose_name_plural': 'Global Departments',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='GlobalRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='registry.globaldepartment')),
            ],
            options={
                'verbose_name': 'Global Role',
                'verbose_name_plural': 'Global Roles',
                'ordering': ['department', 'name'],
            },
        ),
        migrations.CreateModel(
            name='GlobalAppRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(max_length=100)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='registry.globalapp')),
            ],
            options={
                'unique_together': {('app', 'role_name')},
            },
        ),
    ]
