# Generated by Django 6.0.3 on 2026-05-05 02:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Public name of the app (e.g. 'Inventory Pro')", max_length=100)),
                ('system_slug', models.SlugField(help_text="Unique identifier used for routing (e.g. 'inventory-pro')", unique=True)),
                ('description', models.TextField(blank=True, help_text='Detailed explanation of what the app does.')),
                ('url_conf_path', models.CharField(help_text="The Python path to the app's URLs", max_length=255)),
                ('icon_class', models.CharField(default='fas fa-cube', help_text='FontAwesome class for the dashboard icon.', max_length=50)),
                ('is_premium', models.BooleanField(default=False, help_text='If true, only tenants with premium subscriptions can use this.')),
                ('is_active', models.BooleanField(default=True, help_text='If false, this app is hidden from all catalogs.')),
                ('short_description', models.CharField(blank=True, max_length=255)),
                ('base_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('link_url_1', models.URLField(blank=True, help_text='e.g. Documentation', null=True)),
                ('link_label_1', models.CharField(blank=True, default='Documentation', max_length=50)),
                ('link_url_2', models.URLField(blank=True, help_text='e.g. Support', null=True)),
                ('link_label_2', models.CharField(blank=True, default='Support', max_length=50)),
                ('is_default', models.BooleanField(default=False, help_text='Automatically install this app for every new tenant.')),
            ],
            options={
                'verbose_name': 'Global App',
                'verbose_name_plural': 'Global Apps',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='GlobalAppScreenshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField()),
                ('caption', models.CharField(blank=True, max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screenshots', to='registry.globalapp')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='GlobalDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='registry.globalapp')),
            ],
            options={
                'verbose_name': 'Global Department',
                'verbose_name_plural': 'Global Departments',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='GlobalRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='registry.globaldepartment')),
            ],
            options={
                'verbose_name': 'Global Role',
                'verbose_name_plural': 'Global Roles',
                'ordering': ['department', 'name'],
            },
        ),
        migrations.CreateModel(
            name='GlobalAppRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(max_length=100)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='registry.globalapp')),
            ],
            options={
                'unique_together': {('app', 'role_name')},
            },
        ),
    ]
