# Generated by Django 6.0.3 on 2026-03-25 03:33

import apps.demo.small_biz.branding.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('registry', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Branding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='Your Company Name', max_length=255)),
                ('logo', models.ImageField(blank=True, null=True, upload_to=apps.demo.small_biz.branding.models.tenant_directory_path)),
                ('favicon', models.ImageField(blank=True, null=True, upload_to=apps.demo.small_biz.branding.models.tenant_directory_path)),
                ('address_line_1', models.CharField(blank=True, max_length=255)),
                ('address_line_2', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state_province', models.CharField(blank=True, max_length=100)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('country', models.CharField(default='United States', max_length=100)),
                ('phone_number', models.CharField(blank=True, max_length=50)),
                ('email_address', models.EmailField(blank=True, max_length=254)),
                ('website_url', models.URLField(blank=True)),
                ('tax_number', models.CharField(blank=True, max_length=100)),
                ('default_tax_rate', models.DecimalField(decimal_places=4, default=0.0, max_digits=6, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('currency_symbol', models.CharField(default='$', max_length=10)),
            ],
            options={
                'verbose_name': 'Company Branding',
                'verbose_name_plural': 'Company Branding',
            },
        ),
        migrations.CreateModel(
            name='RegistryApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon_class', models.CharField(default='fas fa-cube', help_text='FontAwesome class', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='AppRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(max_length=100)),
                ('permissions_description', models.TextField(blank=True)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='branding.registryapp')),
            ],
            options={
                'unique_together': {('app', 'role_name')},
            },
        ),
        migrations.CreateModel(
            name='UserAppAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('app_role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_assignments', to='registry.globalrole')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_assignments', to='registry.globaldepartment')),
                ('global_app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registry.globalapp')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='app_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User App Assignment',
                'verbose_name_plural': 'User App Assignments',
                'unique_together': {('user', 'global_app')},
            },
        ),
    ]
