# Generated by Django 6.0.3 on 2026-05-05 02:14

import django.db.models.deletion
import django.utils.timezone
import django_ckeditor_5.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('registry', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=250, unique=True)),
                ('content', models.TextField()),
                ('category', models.CharField(choices=[('General', 'General'), ('Benefits', 'Benefits'), ('Conduct', 'Conduct'), ('Safety', 'Safety')], default='General', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmploymentStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('is_active_status', models.BooleanField(default=True)),
                ('color_code', models.CharField(blank=True, default='#2dce89', max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PayBand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('min_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('max_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('currency', models.CharField(default='USD', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(blank=True, max_length=20, unique=True)),
                ('is_management', models.BooleanField(default=False, help_text='Grants administrative dashboard access')),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='TemplateCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('icon', models.CharField(help_text='Lucide icon name or Emoji', max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Template Categories',
            },
        ),
        migrations.CreateModel(
            name='WorkLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AppSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starting_associate_number', models.PositiveIntegerField(default=1000)),
                ('current_sequence_value', models.PositiveIntegerField(default=0)),
                ('associate_id_prefix', models.CharField(default='EMP', help_text='e.g. EMP', max_length=10)),
                ('associate_id_suffix', models.CharField(blank=True, help_text='e.g. HQ', max_length=10)),
                ('use_year_in_id', models.BooleanField(default=True)),
                ('admin_users', models.ManyToManyField(blank=True, related_name='admin_of_apps', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'App Setting',
                'verbose_name_plural': 'App Settings',
            },
        ),
        migrations.CreateModel(
            name='Associate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('associate_id', models.CharField(blank=True, help_text='Leave blank to auto-generate based on App Settings', max_length=50, unique=True)),
                ('hire_date', models.DateField(default=django.utils.timezone.now)),
                ('termination_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profiles/')),
                ('current_salary', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other'), ('P', 'Prefer not to say')], default='P', max_length=30)),
                ('ethnicity', models.CharField(blank=True, choices=[('W', 'White'), ('H', 'Hispanic'), ('B', 'Black'), ('A', 'Asian'), ('O', 'Other'), ('P', 'Prefer not to say')], default='P', max_length=30)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('personal_email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True)),
                ('address2', models.TextField(blank=True)),
                ('city', models.TextField(blank=True)),
                ('state', models.TextField(blank=True)),
                ('zip', models.TextField(blank=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('sick_leave_used', models.DecimalField(decimal_places=2, default=0.0, help_text='Total sick leave used', max_digits=5)),
                ('annual_leave_used', models.DecimalField(decimal_places=2, default=0.0, help_text='Total annual leave used', max_digits=5)),
                ('other_leave_used', models.DecimalField(decimal_places=2, default=0.0, help_text='Other leave used', max_digits=5)),
                ('pto_accrued', models.DecimalField(decimal_places=2, default=0.0, help_text='Total PTO accrued', max_digits=6)),
                ('pto_used', models.DecimalField(decimal_places=2, default=0.0, help_text='Total PTO used', max_digits=6)),
                ('pto_balance', models.DecimalField(decimal_places=2, default=0.0, help_text='Calculated remaining balance', max_digits=6)),
                ('emergency_contact_name', models.CharField(blank=True, max_length=100)),
                ('emergency_contact_relationship', models.CharField(blank=True, max_length=50)),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=20)),
                ('reports_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='direct_reports', to='associate.associate')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='associate_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AssociateDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(max_length=50)),
                ('file', models.FileField(upload_to='associate_docs/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('associate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='associate.associate')),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('code', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_departments', to='associate.associate')),
            ],
        ),
        migrations.AddField(
            model_name='associate',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='associate.department'),
        ),
        migrations.AddField(
            model_name='associate',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='associates', to='associate.employmentstatus'),
        ),
        migrations.AddField(
            model_name='associate',
            name='pay_band',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='associate.payband'),
        ),
        migrations.CreateModel(
            name='PerformanceReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved')], default='draft', max_length=20)),
                ('review_date', models.DateField(default=django.utils.timezone.now)),
                ('review_period_start', models.DateField(blank=True, null=True)),
                ('review_period_end', models.DateField(blank=True, null=True)),
                ('next_review_date', models.DateField(blank=True, null=True)),
                ('performance_rating', models.IntegerField(blank=True, choices=[(1, 'Unsatisfactory'), (2, 'Needs Improvement'), (3, 'Meets Expectations'), (4, 'Exceeds Expectations'), (5, 'Exceptional')], null=True)),
                ('okr_summary', models.TextField(blank=True, help_text='Objectives and Key Results Progress', null=True)),
                ('kpi_metrics', models.JSONField(blank=True, default=dict, help_text='Role-specific metrics')),
                ('project_completion_rate', models.DecimalField(decimal_places=2, default=0.0, help_text='Percentage finished on time', max_digits=5)),
                ('leadership_rating', models.IntegerField(choices=[(1, 'Unsatisfactory'), (2, 'Needs Improvement'), (3, 'Meets Expectations'), (4, 'Exceeds Expectations'), (5, 'Exceptional')], default=3)),
                ('communication_rating', models.IntegerField(choices=[(1, 'Unsatisfactory'), (2, 'Needs Improvement'), (3, 'Meets Expectations'), (4, 'Exceeds Expectations'), (5, 'Exceptional')], default=3)),
                ('technical_ability_rating', models.IntegerField(choices=[(1, 'Unsatisfactory'), (2, 'Needs Improvement'), (3, 'Meets Expectations'), (4, 'Exceeds Expectations'), (5, 'Exceptional')], default=3)),
                ('feedback', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Executive Feedback')),
                ('self_assessment_score', models.IntegerField(blank=True, choices=[(1, 'Unsatisfactory'), (2, 'Needs Improvement'), (3, 'Meets Expectations'), (4, 'Exceeds Expectations'), (5, 'Exceptional')], null=True)),
                ('self_assessment_comments', models.TextField(blank=True, null=True)),
                ('peer_feedback_summary', models.TextField(blank=True, help_text='Feedback from colleagues', null=True)),
                ('skills_gap_analysis', models.TextField(blank=True, help_text='Areas needing improvement', null=True)),
                ('training_progress', models.TextField(blank=True, help_text='Courses taken', null=True)),
                ('goals_for_next_period', models.TextField(blank=True, null=True)),
                ('goals_met', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('associate', models.ForeignKey(help_text='The employee being reviewed', on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='associate.associate')),
                ('reviewer', models.ForeignKey(help_text='Direct supervisor', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews_conducted', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Performance Review',
                'verbose_name_plural': 'Performance Reviews',
                'ordering': ['-review_date'],
            },
        ),
        migrations.AddField(
            model_name='associate',
            name='position',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='associate.position'),
        ),
        migrations.CreateModel(
            name='SalaryHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('change_reason', models.CharField(help_text='e.g., Annual Raise, Promotion', max_length=255)),
                ('effective_date', models.DateField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('associate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_history', to='associate.associate')),
            ],
            options={
                'ordering': ['-effective_date'],
            },
        ),
        migrations.CreateModel(
            name='CKTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField(blank=True)),
                ('content', django_ckeditor_5.fields.CKEditor5Field(help_text='The raw HTML/CKEditor content for the template')),
                ('thumbnail_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='templates', to='associate.templatecategory')),
            ],
        ),
        migrations.CreateModel(
            name='TenantAppInstallation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('installed_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True, help_text="If false, this app is hidden from the tenant's dashboard.")),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='installations', to='registry.globalapp')),
                ('installed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tenant App Installation',
                'verbose_name_plural': 'Tenant App Installations',
                'unique_together': {('app',)},
            },
        ),
        migrations.CreateModel(
            name='UserSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filled_content', models.TextField()),
                ('is_draft', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('base_template', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='associate.cktemplate')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='associate',
            name='work_location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='associate.worklocation'),
        ),
        migrations.CreateModel(
            name='UserAppAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('installation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='associate.tenantappinstallation')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registry.globalrole')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='associate_app_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User App Assignment',
                'verbose_name_plural': 'User App Assignments',
                'unique_together': {('user', 'installation')},
            },
        ),
    ]
