# Generated by Django 6.0.3 on 2026-05-05 02:14

import django.db.models.deletion
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('discount_percent', models.PositiveIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('icon_tag', models.CharField(default='box', help_text='Lucide icon name', max_length=50)),
                ('short_description', models.CharField(max_length=255)),
                ('full_description', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('link_url_1', models.URLField(blank=True, help_text='External URL 1 (e.g. Documentation)', null=True)),
                ('link_label_1', models.CharField(blank=True, default='Documentation', max_length=50, null=True)),
                ('link_url_2', models.URLField(blank=True, help_text='External URL 2 (e.g. Support)', null=True)),
                ('link_label_2', models.CharField(blank=True, default='Support', max_length=50, null=True)),
                ('assigned_tenants', models.ManyToManyField(blank=True, related_name='installed_apps', to='customers.client')),
            ],
        ),
        migrations.CreateModel(
            name='AppFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_text', models.CharField(max_length=255)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='marketplace.app')),
            ],
        ),
        migrations.CreateModel(
            name='AppRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='marketplace.app')),
            ],
        ),
        migrations.CreateModel(
            name='AppScreenshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video')], default='image', max_length=10)),
                ('image_url', models.URLField(help_text='Direct URL to image or Video ID')),
                ('caption', models.CharField(blank=True, max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screenshots', to='marketplace.app')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='AppTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('setup_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('billing_cycle', models.CharField(default='month', max_length=20)),
                ('is_subscription', models.BooleanField(default=True)),
                ('paypal_plan_id', models.CharField(blank=True, help_text='PayPal Subscription Plan ID', max_length=100)),
                ('is_featured', models.BooleanField(default=False)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tiers', to='marketplace.app')),
            ],
        ),
        migrations.CreateModel(
            name='KBArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', django_ckeditor_5.fields.CKEditor5Field()),
                ('category', models.CharField(default='General', max_length=50)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kb_articles', to='marketplace.app')),
            ],
        ),
    ]
