"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-g1y*2brm=-663roz0)f2i^b$p=g$1m7h@a1so_pp&#d6oqr_ur'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["127.0.0.1", 'localhost', '.localhost']

# Application definition
# Ensure django_tenants is at the top
SHARED_APPS = (
    'django_tenants',  # mandatory
    'customers',       # your app containing Client/Domain models
    'django.contrib.contenttypes',
    'django.contrib.auth',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.admin',
    'django.contrib.staticfiles',  # Added to ensure static files are handled

    # --- GLOBAL REGISTRY & MARKETPLACE ---
    'marketplace',  # Global catalog of apps/services
    'registry',     # Global registry of Depts/Roles
)

TENANT_APPS = (
    'django.contrib.contenttypes',
    'django.contrib.auth',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.admin',
    'django.contrib.staticfiles',  # Added to ensure static files are handled
    # Add your tenant-specific apps here
    'chores',
    'apps.demo.small_biz.inventory',
    'apps.demo.small_biz.pos',
    'apps.demo.small_biz.acct_customer',
    'apps.demo.small_biz.invoicing',
    'apps.demo.small_biz.branding',
    # 'registry',
    # Adding it here ensures 'Branding', 'UserAppAssignment', etc.,
    # are created in every new tenant schema you create.

)

INSTALLED_APPS = list(SHARED_APPS) + [app for app in TENANT_APPS if app not in SHARED_APPS]

# Point to your custom models (we will create these next)

TENANT_MODEL = 'customers.Client'
TENANT_DOMAIN_MODEL = 'customers.Domain'

MIDDLEWARE = [
    'django_tenants.middleware.main.TenantMainMiddleware', # MUST BE FIRST
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    # 2. YOUR CUSTOM MIDDLEWARE (The Roof)
    # The format is: 'folder_name.file_name.Class_Name'
    'core.middleware.PlanAccessMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',



]



# --- ROUTING ---
# This tells django-tenants to ignore the port when looking up the tenant
# in the database. This is the "Official" way to avoid duplicate domains.
TENANT_DOMAIN_MODEL_ATTRIBUTES = {'port': False}

# Also ensure this is True to help with routing
SET_URLCONF_ALL_REQUESTS = True

# 3. ROUTING ENGINE
ROOT_URLCONF = 'core.urls'
PUBLIC_SCHEMA_URLCONF = 'core.urls_public'
TENANT_URLCONF = 'core.urls'

# 4. CRITICAL: Identify which schema is the "Landing Page"
# If this is missing, the middleware might not switch contexts correctly
PUBLIC_SCHEMA_NAME = 'public'

CSRF_USE_SESSIONS = True
SESSION_COOKIE_DOMAIN = None
CSRF_COOKIE_DOMAIN = None
SESSION_COOKIE_SAMESITE = 'Lax'
CSRF_COOKIE_SAMESITE = 'Lax'
SESSION_COOKIE_SECURE = False
CSRF_COOKIE_SECURE = False

CSRF_TRUSTED_ORIGINS = [
    'http://*.localhost:8000',
    'http://localhost:8000',
    'http://127.0.0.1:8000',
]

# Allow redirects to the public landing page domain from subdomains
ALLOWED_REDIRECT_HOSTS = ['localhost', '127.0.0.1']

# Default redirect after logout if no ?next= is provided
LOGOUT_REDIRECT_URL = 'http://localhost:8000/'

LOGIN_REDIRECT_URL = '/accounts/profile/'

SHOW_PUBLIC_IF_NO_TENANT_FOUND = True

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django_tenants.postgresql_backend', # Use the tenant backend
        'NAME': 'django_project_tenant_2_db',
        'USER': 'traxx_admin',
        'PASSWORD': 'Malware123?',
        'HOST': '192.168.1.188',
    }
}

DATABASE_ROUTERS = (
    'django_tenants.routers.TenantSyncRouter',
)


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

# STATIC_URL = 'static/'


# --- STATIC FILES CONFIGURATION ---
STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Ensure Django looks in the global static folder for shared assets
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]

# --- MEDIA FILES CONFIGURATION ---
# Base directory for all media
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# URL prefix for media files
MEDIA_URL = '/media/'

# For development, you can output emails to the console:
# EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

# For production (e.g., Gmail):
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'your-email@gmail.com'
EMAIL_HOST_PASSWORD = 'your-app-password'
DEFAULT_FROM_EMAIL = 'Your Business Name <your-email@gmail.com>'
SALES_TEAM_EMAIL = 'sales@yourbusiness.com'

