"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-g1y*2brm=-663roz0)f2i^b$p=g$1m7h@a1so_pp&#d6oqr_ur'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["127.0.0.1", 'localhost', '.localhost']

# Application definition
# Ensure django_tenants is at the top
SHARED_APPS = (
    'django_tenants',  # mandatory
    'tailwind',
    'django_ckeditor_5',
    'theme',
    'customers',       # your app containing Client/Domain models
    'django.contrib.contenttypes',
    'django.contrib.auth',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.admin',
    'django.contrib.staticfiles',  # Added to ensure static files are handled

    # --- GLOBAL REGISTRY & MARKETPLACE ---
    'registry',  # Global registry of Depts/Roles
    'marketplace',  # Global catalog of apps/services
    # 'billing',   # New Software Library and Billing

)

TENANT_APPS = (
    'django.contrib.contenttypes',
    'django.contrib.auth',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.admin',
    'django.contrib.staticfiles',  # Added to ensure static files are handled
    # Add your tenant-specific apps here
    'tailwind',
    'theme',
    'django_ckeditor_5',
    'chores',
    'apps.finance.accounting',
    'apps.finance.payroll',
    'apps.operations.crm',
    'apps.operations.projects',
    'apps.demo.small_biz.inventory',
    'apps.demo.small_biz.pos',
    'apps.demo.small_biz.acct_customer',
    'apps.demo.small_biz.invoicing',
    'apps.demo.small_biz.branding',
    # 'apps.demo.small_biz.employee',
    # 'apps.demo.small_biz.expense',
    'associate',


)

INSTALLED_APPS = list(SHARED_APPS) + [app for app in TENANT_APPS if app not in SHARED_APPS]

# Point to your custom models (we will create these next)

TENANT_MODEL = 'customers.Client'
TENANT_DOMAIN_MODEL = 'customers.Domain'


# Default is often 'DENY'. Change it to allow iframes on the same domain.
X_FRAME_OPTIONS = 'SAMEORIGIN'


MIDDLEWARE = [
    'django_tenants.middleware.main.TenantMainMiddleware', # MUST BE FIRST
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    # 2. YOUR CUSTOM MIDDLEWARE (The Roof)
    # The format is: 'folder_name.file_name.Class_Name'
    'core.middleware.PlanAccessMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# --- ROUTING ---
# This tells django-tenants to ignore the port when looking up the tenant
# in the database. This is the "Official" way to avoid duplicate domains.
TENANT_DOMAIN_MODEL_ATTRIBUTES = {'port': False}

# Also ensure this is True to help with routing
SET_URLCONF_ALL_REQUESTS = True

# 3. ROUTING ENGINE
ROOT_URLCONF = 'core.urls'
PUBLIC_SCHEMA_URLCONF = 'core.urls_public'
TENANT_URLCONF = 'core.urls'

# 4. CRITICAL: Identify which schema is the "Landing Page"
# If this is missing, the middleware might not switch contexts correctly
PUBLIC_SCHEMA_NAME = 'public'

CSRF_USE_SESSIONS = True
SESSION_COOKIE_DOMAIN = None
CSRF_COOKIE_DOMAIN = None
SESSION_COOKIE_SAMESITE = 'Lax'
CSRF_COOKIE_SAMESITE = 'Lax'
SESSION_COOKIE_SECURE = False
CSRF_COOKIE_SECURE = False

CSRF_TRUSTED_ORIGINS = [
    'http://*.localhost:8000',
    'http://localhost:8000',
    'http://127.0.0.1:8000',
]

# Allow redirects to the public landing page domain from subdomains
ALLOWED_REDIRECT_HOSTS = ['localhost', '127.0.0.1']

# Default redirect after logout if no ?next= is provided
LOGOUT_REDIRECT_URL = 'http://localhost:8000/'

LOGIN_REDIRECT_URL = '/accounts/profile/'

SHOW_PUBLIC_IF_NO_TENANT_FOUND = True

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django_tenants.postgresql_backend', # Use the tenant backend
        'NAME': 'django_project_tenant_2_db',
        'USER': 'traxx_admin',
        'PASSWORD': 'Malware123?',
        'HOST': '192.168.1.188',
    }
}

DATABASE_ROUTERS = (
    'django_tenants.routers.TenantSyncRouter',
)


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# CKEditor Configuration
CKEDITOR_UPLOAD_PATH = "uploads/ckeditor_5/"  # This is relative to your MEDIA_ROOT
CKEDITOR_IMAGE_BACKEND = "pillow"           # Requires 'pip install pillow'

# Optional: Default Config for the RichTextField
CKEDITOR_CONFIGS = {
    'default': {
        'toolbar': 'full',
        'height': 300,
        'width': '100%',
    },
}

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

# STATIC_URL = 'static/'


# --- TAILWIND CONFIGURATION ---
# This must match the name of the app you created with 'tailwind init'
TAILWIND_APP_NAME = 'theme'

# Required for the tailwind hot-reload and debug tools
INTERNAL_IPS = [
    "127.0.0.1",
    "localhost",
]

# --- STATIC FILES CONFIGURATION ---
STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Use the / operator for reliable Windows path joining
STATICFILES_DIRS = [
    BASE_DIR / 'static',
    BASE_DIR / 'theme' / 'static',
]

# Ensure these finders are active
STATICFILES_FINDERS = [
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
]

# --- MEDIA FILES CONFIGURATION ---
# URL prefix for media files
MEDIA_URL = '/media/'
# Base directory for all media
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
DEFAULT_FILE_STORAGE = 'django_tenants.storage.TenantFileSystemStorage'

# This defines the subfolder structure inside your MEDIA_ROOT.
# Leaving it as an empty string "" is common, or you can use "tenants"
MULTITENANT_RELATIVE_MEDIA_ROOT = ""

customColorPalette = [
        {
            'color': 'hsl(4, 90%, 58%)',
            'label': 'Red'
        },
        {
            'color': 'hsl(340, 82%, 52%)',
            'label': 'Pink'
        },
        {
            'color': 'hsl(291, 64%, 42%)',
            'label': 'Purple'
        },
        {
            'color': 'hsl(262, 52%, 47%)',
            'label': 'Deep Purple'
        },
        {
            'color': 'hsl(231, 48%, 48%)',
            'label': 'Indigo'
        },
        {
            'color': 'hsl(207, 90%, 54%)',
            'label': 'Blue'
        },
    ]

CKEDITOR_5_CUSTOM_CSS = 'path_to.css' # optional
CKEDITOR_5_FILE_STORAGE = "path_to_storage.CustomStorage" # optional
CKEDITOR_5_UPLOAD_FILE_VIEW_NAME = "custom_upload_file" # Optional: if using custom view

licenseKey: 'GPL'
CKEDITOR_5_CONFIGS = {
    'default': {
        'licenseKey': 'GPL',  # Required for CKEditor 5 v37+
        'toolbar': {
            'items': [
                'heading', '|', 'bold', 'italic', 'link',
                'bulletedList', 'numberedList', 'blockQuote', 'imageUpload',
            ],
        }
    },
    'extends': {
        'licenseKey': 'GPL', # Required here as well
        'blockToolbar': [
            'paragraph', 'heading1', 'heading2', 'heading3',
            '|',
            'bulletedList', 'numberedList',
            '|',
            'blockQuote',
        ],
        "toolbar": [
            "heading", "|", "outdent", "indent", "|", "bold", "italic", "link", "underline", "strikethrough",
            "code", "subscript", "superscript", "highlight", "|", "codeBlock", "sourceEditing", "insertImage",
            "imageUpload", "blockQuote", "insertTable", "mediaEmbed", "list", "numberedList", "todoList", "|",
            "fontSize", "fontFamily", "fontColor", "fontBackgroundColor", "alignment", "|", "linkImage", "uploadImage",
        ],
         "image": {
            "toolbar": [
                "imageTextAlternative", "|", "imageStyle:alignLeft",
                "imageStyle:alignRight", "imageStyle:alignCenter", "imageStyle:side", "|",
            ],
            "styles": [
                "full", "side", "alignLeft", "alignRight", "alignCenter",
            ],
        },
        'table': {
            'contentToolbar': [
                'tableColumn', 'tableRow', 'mergeTableCells',
                'tableProperties', 'tableCellProperties'
            ],
            'tableProperties': {
                'borderColors': customColorPalette,
                'backgroundColors': customColorPalette
            },
            'tableCellProperties': {
                'borderColors': customColorPalette,
                'backgroundColors': customColorPalette
            }
        },
        'heading': {
            'options': [
                {'model': 'paragraph', 'title': 'Paragraph', 'class': 'ck-heading_paragraph'},
                {'model': 'heading1', 'view': 'h1', 'title': 'Heading 1', 'class': 'ck-heading_heading1'},
                {'model': 'heading2', 'view': 'h2', 'title': 'Heading 2', 'class': 'ck-heading_heading2'},
                {'model': 'heading3', 'view': 'h3', 'title': 'Heading 3', 'class': 'ck-heading_heading3'}
            ]
        }
    },
    'list': {
        'licenseKey': 'GPL',
        'properties': {
            'styles': True,
            'startIndex': True,
            'reversed': True,
        }
    }
}

# Define a constant in settings.py to specify file upload permissions
CKEDITOR_5_FILE_UPLOAD_PERMISSION = "staff", "authenticated",

# Possible values: "staff", "authenticated", "any"
CK_EDITOR_5_UPLOAD_FILE_VIEW_NAME = "custom_upload_file"

# For development, you can output emails to the console:
# EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

# For production (e.g., Gmail):
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'your-email@gmail.com'
EMAIL_HOST_PASSWORD = 'your-app-password'
DEFAULT_FROM_EMAIL = 'Your Business Name <your-email@gmail.com>'
SALES_TEAM_EMAIL = 'sales@yourbusiness.com'

