# Generated by Django 6.0.3 on 2026-03-27 00:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the project', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Detailed description of the project')),
                ('start_date', models.DateField(help_text='When the project started')),
                ('end_date', models.DateField(blank=True, help_text='Expected or actual end date of the project', null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('on_hold', 'On Hold'), ('cancelled', 'Cancelled')], default='pending', help_text='Current status of the project', max_length=20)),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the task', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Detailed description of the task')),
                ('assigned_to', models.CharField(blank=True, help_text='Person assigned to this task', max_length=100)),
                ('due_date', models.DateField(blank=True, help_text='When the task is due', null=True)),
                ('status', models.CharField(choices=[('todo', 'To Do'), ('in_progress', 'In Progress'), ('done', 'Done'), ('blocked', 'Blocked')], default='todo', help_text='Current status of the task', max_length=20)),
                ('project', models.ForeignKey(help_text='The project this task belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='projects.project')),
            ],
            options={
                'ordering': ['due_date'],
            },
        ),
    ]
